var verbs = [
  { kanji:'会う', kana:'あう', type:'I', level:'N5', meaning:'见面' },
  { kanji:'開く', kana:'あく', type:'I', level:'N5', meaning:'开（自动）' },
  { kanji:'開ける', kana:'あける', type:'II', level:'N5', meaning:'打开（他动）' },
  { kanji:'上げる', kana:'あげる', type:'II', level:'N5', meaning:'举起、给' },
  { kanji:'遊ぶ', kana:'あそぶ', type:'I', level:'N5', meaning:'玩' },
  { kanji:'洗う', kana:'あらう', type:'I', level:'N5', meaning:'洗' },
  { kanji:'ある', kana:'ある', type:'I', level:'N5', exceptions:{nai:'ない'}, meaning:'有、在（无生命）' },
  { kanji:'歩く', kana:'あるく', type:'I', level:'N5', meaning:'走路' },
  { kanji:'言う', kana:'いう', type:'I', level:'N5', meaning:'说' },
  { kanji:'行く', kana:'いく', type:'I', level:'N5', exceptions:{te:'いって',ta:'いった'}, meaning:'去' },
  { kanji:'いる', kana:'いる', type:'II', level:'N5', meaning:'在（有生命）' },
  { kanji:'入れる', kana:'いれる', type:'II', level:'N5', meaning:'放入' },
  { kanji:'歌う', kana:'うたう', type:'I', level:'N5', meaning:'唱歌' },
  { kanji:'生まれる', kana:'うまれる', type:'II', level:'N5', meaning:'出生' },
  { kanji:'売る', kana:'うる', type:'I', level:'N5', meaning:'卖' },
  { kanji:'起きる', kana:'おきる', type:'II', level:'N5', meaning:'起床' },
  { kanji:'置く', kana:'おく', type:'I', level:'N5', meaning:'放置' },
  { kanji:'教える', kana:'おしえる', type:'II', level:'N5', meaning:'教' },
  { kanji:'押す', kana:'おす', type:'I', level:'N5', meaning:'推、按' },
  { kanji:'覚える', kana:'おぼえる', type:'II', level:'N5', meaning:'记住' },
  { kanji:'思う', kana:'おもう', type:'I', level:'N5', meaning:'想、认为' },
  { kanji:'買う', kana:'かう', type:'I', level:'N5', meaning:'买' },
  { kanji:'返す', kana:'かえす', type:'I', level:'N5', meaning:'归还' },
  { kanji:'帰る', kana:'かえる', type:'I', level:'N5', meaning:'回去' },
  { kanji:'書く', kana:'かく', type:'I', level:'N5', meaning:'写' },
  { kanji:'かける', kana:'かける', type:'II', level:'N5', meaning:'打（电话）' },
  { kanji:'貸す', kana:'かす', type:'I', level:'N5', meaning:'借出' },
  { kanji:'被る', kana:'かぶる', type:'I', level:'N5', meaning:'戴（帽子）' },
  { kanji:'借りる', kana:'かりる', type:'II', level:'N5', meaning:'借入' },
  { kanji:'消える', kana:'きえる', type:'II', level:'N5', meaning:'消失' },
  { kanji:'聞く', kana:'きく', type:'I', level:'N5', meaning:'听、问' },
  { kanji:'切る', kana:'きる', type:'I', level:'N5', meaning:'切、剪' },
  { kanji:'着る', kana:'きる', type:'II', level:'N5', meaning:'穿（衣服）' },
  {
    kanji:'来る', kana:'くる', type:'III', level:'N5', meaning:'来',
    meaningOverrides:{
      passive:{
        text:'因为有人来而受到影响',
        speech:'因为有人来而受到影响',
        special:true
      }
    }
  },
  { kanji:'消す', kana:'けす', type:'I', level:'N5', meaning:'关掉、删除' },
  { kanji:'答える', kana:'こたえる', type:'II', level:'N5', meaning:'回答' },
  { kanji:'困る', kana:'こまる', type:'I', level:'N5', meaning:'为难' },
  { kanji:'咲く', kana:'さく', type:'I', level:'N5', meaning:'开花' },
  { kanji:'差す', kana:'さす', type:'I', level:'N5', meaning:'撑（伞）' },
  { kanji:'死ぬ', kana:'しぬ', type:'I', level:'N5', meaning:'死' },
  { kanji:'閉まる', kana:'しまる', type:'I', level:'N5', meaning:'关闭（自动）' },
  { kanji:'閉める', kana:'しめる', type:'II', level:'N5', meaning:'关闭（他动）' },
  { kanji:'知る', kana:'しる', type:'I', level:'N5', meaning:'知道' },
  { kanji:'吸う', kana:'すう', type:'I', level:'N5', meaning:'吸' },
  { kanji:'住む', kana:'すむ', type:'I', level:'N5', meaning:'居住' },
  { kanji:'する', kana:'する', type:'III', level:'N5', meaning:'做' },
  { kanji:'座る', kana:'すわる', type:'I', level:'N5', meaning:'坐下' },
  { kanji:'出す', kana:'だす', type:'I', level:'N5', meaning:'拿出、寄出' },
  { kanji:'立つ', kana:'たつ', type:'I', level:'N5', meaning:'站立' },
  { kanji:'頼む', kana:'たのむ', type:'I', level:'N5', meaning:'请求' },
  { kanji:'食べる', kana:'たべる', type:'II', level:'N5', meaning:'吃' },
  { kanji:'違う', kana:'ちがう', type:'I', level:'N5', meaning:'不同' },
  { kanji:'使う', kana:'つかう', type:'I', level:'N5', meaning:'使用' },
  { kanji:'作る', kana:'つくる', type:'I', level:'N5', meaning:'制作' },
  { kanji:'付ける', kana:'つける', type:'II', level:'N5', meaning:'打开（灯）' },
  { kanji:'勤める', kana:'つとめる', type:'II', level:'N5', meaning:'工作' },
  { kanji:'出る', kana:'でる', type:'II', level:'N5', meaning:'出去' },
  { kanji:'飛ぶ', kana:'とぶ', type:'I', level:'N5', meaning:'飞' },
  { kanji:'止まる', kana:'とまる', type:'I', level:'N5', meaning:'停下' },
  { kanji:'取る', kana:'とる', type:'I', level:'N5', meaning:'拿、取' },
  { kanji:'撮る', kana:'とる', type:'I', level:'N5', meaning:'拍照' },
  { kanji:'直す', kana:'なおす', type:'I', level:'N5', meaning:'修理' },
  { kanji:'無くなる', kana:'なくなる', type:'I', level:'N5', meaning:'丢失、没有了（自动）' },
  { kanji:'並ぶ', kana:'ならぶ', type:'I', level:'N5', meaning:'排队' },
  { kanji:'並べる', kana:'ならべる', type:'II', level:'N5', meaning:'排列' },
  { kanji:'なる', kana:'なる', type:'I', level:'N5', meaning:'变成' },
  { kanji:'脱ぐ', kana:'ぬぐ', type:'I', level:'N5', meaning:'脱' },
  { kanji:'寝る', kana:'ねる', type:'II', level:'N5', meaning:'睡觉' },
  { kanji:'登る', kana:'のぼる', type:'I', level:'N5', meaning:'攀登' },
  { kanji:'飲む', kana:'のむ', type:'I', level:'N5', meaning:'喝' },
  { kanji:'入る', kana:'はいる', type:'I', level:'N5', meaning:'进入' },
  { kanji:'履く', kana:'はく', type:'I', level:'N5', meaning:'穿（鞋/裤）' },
  { kanji:'始まる', kana:'はじまる', type:'I', level:'N5', meaning:'开始（自动）' },
  { kanji:'始める', kana:'はじめる', type:'II', level:'N5', meaning:'开始（他动）' },
  { kanji:'走る', kana:'はしる', type:'I', level:'N5', meaning:'跑' },
  { kanji:'働く', kana:'はたらく', type:'I', level:'N5', meaning:'工作' },
  {
    kanji:'話す', kana:'はなす', type:'I', level:'N5', meaning:'说、讲', speechMeaning:'说',
    meaningOverrides:{
      causativePassive:{text:'被迫说', speech:'被迫说', sense:'说'}
    }
  },
  { kanji:'払う', kana:'はらう', type:'I', level:'N5', meaning:'支付' },
  { kanji:'降る', kana:'ふる', type:'I', level:'N5', meaning:'下（雨/雪）' },
  { kanji:'曲がる', kana:'まがる', type:'I', level:'N5', meaning:'转弯' },
  { kanji:'待つ', kana:'まつ', type:'I', level:'N5', meaning:'等待' },
  { kanji:'磨く', kana:'みがく', type:'I', level:'N5', meaning:'刷、擦' },
  { kanji:'見せる', kana:'みせる', type:'II', level:'N5', meaning:'给…看' },
  { kanji:'見る', kana:'みる', type:'II', level:'N5', meaning:'看' },
  { kanji:'持つ', kana:'もつ', type:'I', level:'N5', meaning:'拿、持有' },
  { kanji:'休む', kana:'やすむ', type:'I', level:'N5', meaning:'休息' },
  { kanji:'呼ぶ', kana:'よぶ', type:'I', level:'N5', meaning:'叫、称呼' },
  { kanji:'読む', kana:'よむ', type:'I', level:'N5', meaning:'读' },
  { kanji:'分かる', kana:'わかる', type:'I', level:'N5', meaning:'明白' },
  { kanji:'渡る', kana:'わたる', type:'I', level:'N5', meaning:'渡过' },
  { kanji:'渡す', kana:'わたす', type:'I', level:'N5', meaning:'交给' },
  // ===== N4 =====
  { kanji:'合う', kana:'あう', type:'I', level:'N4', meaning:'合适、符合' },
  { kanji:'上がる', kana:'あがる', type:'I', level:'N4', meaning:'上升' },
  { kanji:'集まる', kana:'あつまる', type:'I', level:'N4', meaning:'聚集' },
  { kanji:'集める', kana:'あつめる', type:'II', level:'N4', meaning:'收集' },
  { kanji:'謝る', kana:'あやまる', type:'I', level:'N4', meaning:'道歉' },
  { kanji:'安心する', kana:'あんしんする', type:'III', level:'N4', meaning:'放心' },
  { kanji:'行う', kana:'おこなう', type:'I', level:'N4', meaning:'举行' },
  { kanji:'怒る', kana:'おこる', type:'I', level:'N4', meaning:'生气' },
  { kanji:'落ちる', kana:'おちる', type:'II', level:'N4', meaning:'掉落' },
  { kanji:'思い出す', kana:'おもいだす', type:'I', level:'N4', meaning:'想起' },
  { kanji:'片付ける', kana:'かたづける', type:'II', level:'N4', meaning:'整理' },
  { kanji:'勝つ', kana:'かつ', type:'I', level:'N4', meaning:'赢' },
  { kanji:'通う', kana:'かよう', type:'I', level:'N4', meaning:'来往（上学/上班）' },
  { kanji:'決まる', kana:'きまる', type:'I', level:'N4', meaning:'决定（自动）' },
  { kanji:'決める', kana:'きめる', type:'II', level:'N4', meaning:'决定（他动）' },
  { kanji:'暮れる', kana:'くれる', type:'II', level:'N4', meaning:'天黑、岁末' },
  { kanji:'くれる', kana:'くれる', type:'II', level:'N4', exceptions:{imperative:'くれ'}, meaning:'给（我）' },
  { kanji:'下がる', kana:'さがる', type:'I', level:'N4', meaning:'下降' },
  { kanji:'下げる', kana:'さげる', type:'II', level:'N4', meaning:'降低' },
  { kanji:'差し上げる', kana:'さしあげる', type:'II', level:'N4', meaning:'奉上' },
  { kanji:'騒ぐ', kana:'さわぐ', type:'I', level:'N4', meaning:'吵闹' },
  { kanji:'触る', kana:'さわる', type:'I', level:'N4', meaning:'触摸' },
  { kanji:'準備する', kana:'じゅんびする', type:'III', level:'N4', meaning:'准备' },
  { kanji:'紹介する', kana:'しょうかいする', type:'III', level:'N4', meaning:'介绍' },
  { kanji:'調べる', kana:'しらべる', type:'II', level:'N4', meaning:'调查' },
  { kanji:'過ぎる', kana:'すぎる', type:'II', level:'N4', meaning:'经过' },
  { kanji:'進む', kana:'すすむ', type:'I', level:'N4', meaning:'前进' },
  { kanji:'捨てる', kana:'すてる', type:'II', level:'N4', meaning:'扔掉' },
  { kanji:'滑る', kana:'すべる', type:'I', level:'N4', meaning:'滑' },
  { kanji:'育てる', kana:'そだてる', type:'II', level:'N4', meaning:'养育' },
  { kanji:'倒れる', kana:'たおれる', type:'II', level:'N4', meaning:'倒塌、跌倒' },
  { kanji:'足す', kana:'たす', type:'I', level:'N4', meaning:'添加' },
  { kanji:'建てる', kana:'たてる', type:'II', level:'N4', meaning:'建造' },
  { kanji:'楽しむ', kana:'たのしむ', type:'I', level:'N4', meaning:'享受' },
  { kanji:'足りる', kana:'たりる', type:'II', level:'N4', meaning:'足够' },
  { kanji:'注意する', kana:'ちゅういする', type:'III', level:'N4', meaning:'注意' },
  { kanji:'疲れる', kana:'つかれる', type:'II', level:'N4', meaning:'疲劳' },
  { kanji:'伝える', kana:'つたえる', type:'II', level:'N4', meaning:'传达' },
  { kanji:'続く', kana:'つづく', type:'I', level:'N4', meaning:'继续（自动）' },
  { kanji:'続ける', kana:'つづける', type:'II', level:'N4', meaning:'继续（他动）' },
  { kanji:'包む', kana:'つつむ', type:'I', level:'N4', meaning:'包、裹' },
  { kanji:'釣る', kana:'つる', type:'I', level:'N4', meaning:'钓鱼' },
  { kanji:'出かける', kana:'でかける', type:'II', level:'N4', meaning:'外出' },
  { kanji:'出来る', kana:'できる', type:'II', level:'N4', meaning:'会、完成' },
  { kanji:'手伝う', kana:'てつだう', type:'I', level:'N4', meaning:'帮忙' },
  { kanji:'飛ばす', kana:'とばす', type:'I', level:'N4', meaning:'放飞' },
  { kanji:'届ける', kana:'とどける', type:'II', level:'N4', meaning:'送到' },
  { kanji:'泊まる', kana:'とまる', type:'I', level:'N4', meaning:'住宿' },
  { kanji:'直る', kana:'なおる', type:'I', level:'N4', meaning:'修好' },
  { kanji:'治る', kana:'なおる', type:'I', level:'N4', meaning:'痊愈' },
  { kanji:'泣く', kana:'なく', type:'I', level:'N4', meaning:'哭' },
  { kanji:'無くす', kana:'なくす', type:'I', level:'N4', meaning:'弄丢' },
  { kanji:'慣れる', kana:'なれる', type:'II', level:'N4', meaning:'习惯' },
  { kanji:'逃げる', kana:'にげる', type:'II', level:'N4', meaning:'逃跑' },
  { kanji:'似る', kana:'にる', type:'II', level:'N4', meaning:'像' },
  { kanji:'盗む', kana:'ぬすむ', type:'I', level:'N4', meaning:'偷' },
  { kanji:'残る', kana:'のこる', type:'I', level:'N4', meaning:'留下' },
  { kanji:'乗り換える', kana:'のりかえる', type:'II', level:'N4', meaning:'换乘' },
  { kanji:'運ぶ', kana:'はこぶ', type:'I', level:'N4', meaning:'搬运' },
  { kanji:'貼る', kana:'はる', type:'I', level:'N4', meaning:'贴' },
  { kanji:'引く', kana:'ひく', type:'I', level:'N4', meaning:'拉、引' },
  { kanji:'弾く', kana:'ひく', type:'I', level:'N4', meaning:'弹奏' },
  { kanji:'冷やす', kana:'ひやす', type:'I', level:'N4', meaning:'冰镇' },
  { kanji:'増える', kana:'ふえる', type:'II', level:'N4', meaning:'增加' },
  { kanji:'復習する', kana:'ふくしゅうする', type:'III', level:'N4', meaning:'复习' },
  { kanji:'踏む', kana:'ふむ', type:'I', level:'N4', meaning:'踩' },
  { kanji:'減る', kana:'へる', type:'I', level:'N4', meaning:'减少' },
  { kanji:'褒める', kana:'ほめる', type:'II', level:'N4', meaning:'表扬' },
  { kanji:'負ける', kana:'まける', type:'II', level:'N4', meaning:'输' },
  { kanji:'間違える', kana:'まちがえる', type:'II', level:'N4', meaning:'搞错' },
  { kanji:'間に合う', kana:'まにあう', type:'I', level:'N4', meaning:'赶上' },
  { kanji:'回る', kana:'まわる', type:'I', level:'N4', meaning:'转动' },
  { kanji:'見つかる', kana:'みつかる', type:'I', level:'N4', meaning:'被找到' },
  { kanji:'見つける', kana:'みつける', type:'II', level:'N4', meaning:'找到' },
  { kanji:'迎える', kana:'むかえる', type:'II', level:'N4', meaning:'迎接' },
  { kanji:'戻る', kana:'もどる', type:'I', level:'N4', meaning:'返回' },
  { kanji:'約束する', kana:'やくそくする', type:'III', level:'N4', meaning:'约定' },
  { kanji:'痩せる', kana:'やせる', type:'II', level:'N4', meaning:'瘦' },
  { kanji:'止む', kana:'やむ', type:'I', level:'N4', meaning:'停止（雨/雪）' },
  { kanji:'予習する', kana:'よしゅうする', type:'III', level:'N4', meaning:'预习' },
  { kanji:'喜ぶ', kana:'よろこぶ', type:'I', level:'N4', meaning:'高兴' },
  { kanji:'別れる', kana:'わかれる', type:'II', level:'N4', meaning:'分手' },
  { kanji:'沸かす', kana:'わかす', type:'I', level:'N4', meaning:'烧开' },
  { kanji:'笑う', kana:'わらう', type:'I', level:'N4', meaning:'笑' },
  // ===== N3 (约120个) =====
  { kanji:'飽きる', kana:'あきる', type:'II', level:'N3', meaning:'厌倦' },
  { kanji:'諦める', kana:'あきらめる', type:'II', level:'N3', meaning:'放弃' },
  { kanji:'預かる', kana:'あずかる', type:'I', level:'N3', meaning:'保管' },
  { kanji:'温める', kana:'あたためる', type:'II', level:'N3', meaning:'加热' },
  { kanji:'当たる', kana:'あたる', type:'I', level:'N3', meaning:'命中' },
  { kanji:'表す', kana:'あらわす', type:'I', level:'N3', meaning:'表达' },
  { kanji:'言い出す', kana:'いいだす', type:'I', level:'N3', meaning:'说出口' },
  { kanji:'生きる', kana:'いきる', type:'II', level:'N3', meaning:'活' },
  { kanji:'いらっしゃる', kana:'いらっしゃる', type:'I', level:'N3', exceptions:{masu:'いらっしゃいます',imperative:'いらっしゃい'}, meaning:'在/去/来（尊敬）' },
  { kanji:'受ける', kana:'うける', type:'II', level:'N3', meaning:'接受' },
  { kanji:'動かす', kana:'うごかす', type:'I', level:'N3', meaning:'移动（他动）' },
  { kanji:'動く', kana:'うごく', type:'I', level:'N3', meaning:'移动（自动）' },
  { kanji:'失う', kana:'うしなう', type:'I', level:'N3', meaning:'失去' },
  { kanji:'写す', kana:'うつす', type:'I', level:'N3', meaning:'抄写、拍照' },
  { kanji:'映る', kana:'うつる', type:'I', level:'N3', meaning:'映出' },
  { kanji:'選ぶ', kana:'えらぶ', type:'I', level:'N3', meaning:'选择' },
  { kanji:'おっしゃる', kana:'おっしゃる', type:'I', level:'N3', exceptions:{masu:'おっしゃいます',imperative:'おっしゃい'}, meaning:'说（尊敬）' },
  { kanji:'落とす', kana:'おとす', type:'I', level:'N3', meaning:'弄掉' },
  { kanji:'驚く', kana:'おどろく', type:'I', level:'N3', meaning:'吃惊' },
  { kanji:'下りる', kana:'おりる', type:'II', level:'N3', meaning:'下（车/山）' },
  { kanji:'折れる', kana:'おれる', type:'II', level:'N3', meaning:'折断' },
  { kanji:'飼う', kana:'かう', type:'I', level:'N3', meaning:'饲养' },
  { kanji:'返る', kana:'かえる', type:'I', level:'N3', meaning:'返回（自动）' },
  { kanji:'隠れる', kana:'かくれる', type:'II', level:'N3', meaning:'隐藏' },
  { kanji:'かまう', kana:'かまう', type:'I', level:'N3', meaning:'介意' },
  { kanji:'考える', kana:'かんがえる', type:'II', level:'N3', meaning:'思考' },
  { kanji:'聞こえる', kana:'きこえる', type:'II', level:'N3', meaning:'听得见' },
  { kanji:'くださる', kana:'くださる', type:'I', level:'N3', exceptions:{masu:'くださいます',imperative:'ください'}, meaning:'给（我）（尊敬）' },
  { kanji:'比べる', kana:'くらべる', type:'II', level:'N3', meaning:'比较' },
  { kanji:'加える', kana:'くわえる', type:'II', level:'N3', meaning:'添加' },
  { kanji:'経験する', kana:'けいけんする', type:'III', level:'N3', meaning:'体验' },
  { kanji:'喧嘩する', kana:'けんかする', type:'III', level:'N3', meaning:'吵架' },
  { kanji:'こぼれる', kana:'こぼれる', type:'II', level:'N3', meaning:'洒落' },
  { kanji:'込む', kana:'こむ', type:'I', level:'N3', meaning:'拥挤' },
  { kanji:'殺す', kana:'ころす', type:'I', level:'N3', meaning:'杀' },
  { kanji:'探す', kana:'さがす', type:'I', level:'N3', meaning:'寻找' },
  { kanji:'誘う', kana:'さそう', type:'I', level:'N3', meaning:'邀请' },
  { kanji:'支払う', kana:'しはらう', type:'I', level:'N3', meaning:'支付' },
  { kanji:'しまう', kana:'しまう', type:'I', level:'N3', meaning:'收拾、完了' },
  { kanji:'知らせる', kana:'しらせる', type:'II', level:'N3', meaning:'通知' },
  { kanji:'信じる', kana:'しんじる', type:'II', level:'N3', meaning:'相信' },
  { kanji:'過ごす', kana:'すごす', type:'I', level:'N3', meaning:'度过' },
  { kanji:'進める', kana:'すすめる', type:'II', level:'N3', meaning:'推进' },
  { kanji:'すれ違う', kana:'すれちがう', type:'I', level:'N3', meaning:'擦肩而过' },
  { kanji:'倒す', kana:'たおす', type:'I', level:'N3', meaning:'打倒' },
  { kanji:'確かめる', kana:'たしかめる', type:'II', level:'N3', meaning:'确认' },
  { kanji:'捕まえる', kana:'つかまえる', type:'II', level:'N3', meaning:'抓住' },
  { kanji:'付き合う', kana:'つきあう', type:'I', level:'N3', meaning:'交往' },
  { kanji:'伝わる', kana:'つたわる', type:'I', level:'N3', meaning:'传开' },
  { kanji:'手に入れる', kana:'てにいれる', type:'II', level:'N3', meaning:'得到' },
  { kanji:'通る', kana:'とおる', type:'I', level:'N3', meaning:'通过' },
  { kanji:'届く', kana:'とどく', type:'I', level:'N3', meaning:'收到、送达' },
  { kanji:'飛び込む', kana:'とびこむ', type:'I', level:'N3', meaning:'跳入' },
  { kanji:'亡くなる', kana:'なくなる', type:'I', level:'N3', meaning:'去世' },
  { kanji:'投げる', kana:'なげる', type:'II', level:'N3', meaning:'投掷' },
  { kanji:'なさる', kana:'なさる', type:'I', level:'N3', exceptions:{masu:'なさいます',imperative:'なさい'}, meaning:'做（尊敬）' },
  { kanji:'似合う', kana:'にあう', type:'I', level:'N3', meaning:'适合' },
  { kanji:'残す', kana:'のこす', type:'I', level:'N3', meaning:'留下' },
  { kanji:'外す', kana:'はずす', type:'I', level:'N3', meaning:'取下' },
  { kanji:'増やす', kana:'ふやす', type:'I', level:'N3', meaning:'增加' },
  { kanji:'減らす', kana:'へらす', type:'I', level:'N3', meaning:'减少' },
  { kanji:'参る', kana:'まいる', type:'I', level:'N3', meaning:'去/来（谦让）' },
  { kanji:'任せる', kana:'まかせる', type:'II', level:'N3', meaning:'委托' },
  { kanji:'間違う', kana:'まちがう', type:'I', level:'N3', meaning:'弄错' },
  { kanji:'招く', kana:'まねく', type:'I', level:'N3', meaning:'邀请、招致' },
  { kanji:'守る', kana:'まもる', type:'I', level:'N3', meaning:'保护' },
  { kanji:'見える', kana:'みえる', type:'II', level:'N3', meaning:'看得见' },
  { kanji:'申し上げる', kana:'もうしあげる', type:'II', level:'N3', meaning:'说（谦让）' },
  { kanji:'申す', kana:'もうす', type:'I', level:'N3', meaning:'说（谦让）' },
  { kanji:'戻す', kana:'もどす', type:'I', level:'N3', meaning:'恢复、退回' },
  { kanji:'役立つ', kana:'やくだつ', type:'I', level:'N3', meaning:'有用' },
  { kanji:'破る', kana:'やぶる', type:'I', level:'N3', meaning:'弄破、打破' },
  { kanji:'許す', kana:'ゆるす', type:'I', level:'N3', meaning:'原谅' },
  { kanji:'分ける', kana:'わける', type:'II', level:'N3', meaning:'分开' },
  { kanji:'沸く', kana:'わく', type:'I', level:'N3', meaning:'沸腾' },
  // ===== N2 (约180个) =====
  { kanji:'合図する', kana:'あいずする', type:'III', level:'N2', meaning:'发信号' },
  { kanji:'憧れる', kana:'あこがれる', type:'II', level:'N2', meaning:'憧憬' },
  { kanji:'与える', kana:'あたえる', type:'II', level:'N2', meaning:'给予' },
  { kanji:'当てはまる', kana:'あてはまる', type:'I', level:'N2', meaning:'适用' },
  { kanji:'暴れる', kana:'あばれる', type:'II', level:'N2', meaning:'胡闹' },
  { kanji:'余る', kana:'あまる', type:'I', level:'N2', meaning:'剩余' },
  { kanji:'改める', kana:'あらためる', type:'II', level:'N2', meaning:'改正' },
  { kanji:'育児する', kana:'いくじする', type:'III', level:'N2', meaning:'育儿' },
  { kanji:'維持する', kana:'いじする', type:'III', level:'N2', meaning:'维持' },
  { kanji:'意識する', kana:'いしきする', type:'III', level:'N2', meaning:'意识到' },
  { kanji:'移住する', kana:'いじゅうする', type:'III', level:'N2', meaning:'移居' },
  { kanji:'引退する', kana:'いんたいする', type:'III', level:'N2', meaning:'退休' },
  { kanji:'受け入れる', kana:'うけいれる', type:'II', level:'N2', meaning:'接纳' },
  { kanji:'受け取る', kana:'うけとる', type:'I', level:'N2', meaning:'接收' },
  { kanji:'疑う', kana:'うたがう', type:'I', level:'N2', meaning:'怀疑' },
  { kanji:'打つ', kana:'うつ', type:'I', level:'N2', meaning:'打' },
  { kanji:'促す', kana:'うながす', type:'I', level:'N2', meaning:'催促' },
  { kanji:'生み出す', kana:'うみだす', type:'I', level:'N2', meaning:'产生' },
  { kanji:'得る', kana:'える', type:'II', level:'N2', meaning:'获得' },
  { kanji:'演じる', kana:'えんじる', type:'II', level:'N2', meaning:'扮演' },
  { kanji:'追う', kana:'おう', type:'I', level:'N2', meaning:'追赶' },
  { kanji:'扱う', kana:'あつかう', type:'I', level:'N2', meaning:'处理' },
  { kanji:'補う', kana:'おぎなう', type:'I', level:'N2', meaning:'补充' },
  { kanji:'収める', kana:'おさめる', type:'II', level:'N2', meaning:'收下' },
  { kanji:'治める', kana:'おさめる', type:'II', level:'N2', meaning:'治理' },
  { kanji:'恐れる', kana:'おそれる', type:'II', level:'N2', meaning:'害怕' },
  { kanji:'教わる', kana:'おそわる', type:'I', level:'N2', meaning:'受教' },
  { kanji:'落ち着く', kana:'おちつく', type:'I', level:'N2', meaning:'沉着' },
  { kanji:'驚かす', kana:'おどろかす', type:'I', level:'N2', meaning:'惊吓' },
  { kanji:'帯びる', kana:'おびる', type:'II', level:'N2', meaning:'带有' },
  { kanji:'思い込む', kana:'おもいこむ', type:'I', level:'N2', meaning:'深信' },
  { kanji:'及ぶ', kana:'およぶ', type:'I', level:'N2', meaning:'达到' },
  { kanji:'下ろす', kana:'おろす', type:'I', level:'N2', meaning:'取下' },
  { kanji:'解決する', kana:'かいけつする', type:'III', level:'N2', meaning:'解决' },
  { kanji:'開発する', kana:'かいはつする', type:'III', level:'N2', meaning:'开发' },
  { kanji:'省く', kana:'はぶく', type:'I', level:'N2', meaning:'省略、节省' },
  { kanji:'省みる', kana:'かえりみる', type:'II', level:'N2', meaning:'反省、回顾' },
  { kanji:'隠す', kana:'かくす', type:'I', level:'N2', meaning:'隐藏' },
  { kanji:'囲む', kana:'かこむ', type:'I', level:'N2', meaning:'包围' },
  { kanji:'重なる', kana:'かさなる', type:'I', level:'N2', meaning:'重叠' },
  { kanji:'飾る', kana:'かざる', type:'I', level:'N2', meaning:'装饰' },
  { kanji:'数える', kana:'かぞえる', type:'II', level:'N2', meaning:'数' },
  { kanji:'固まる', kana:'かたまる', type:'I', level:'N2', meaning:'凝固' },
  { kanji:'語る', kana:'かたる', type:'I', level:'N2', meaning:'讲述' },
  { kanji:'悲しむ', kana:'かなしむ', type:'I', level:'N2', meaning:'悲伤' },
  { kanji:'我慢する', kana:'がまんする', type:'III', level:'N2', meaning:'忍耐' },
  { kanji:'かむ', kana:'かむ', type:'I', level:'N2', meaning:'咬' },
  { kanji:'渇く', kana:'かわく', type:'I', level:'N2', meaning:'口渴' },
  { kanji:'乾く', kana:'かわく', type:'I', level:'N2', meaning:'干燥' },
  { kanji:'聞き取る', kana:'ききとる', type:'I', level:'N2', meaning:'听懂' },
  { kanji:'刻む', kana:'きざむ', type:'I', level:'N2', meaning:'刻、切碎' },
  { kanji:'築く', kana:'きずく', type:'I', level:'N2', meaning:'构筑' },
  { kanji:'気付く', kana:'きづく', type:'I', level:'N2', meaning:'注意到' },
  { kanji:'禁止する', kana:'きんしする', type:'III', level:'N2', meaning:'禁止' },
  { kanji:'腐る', kana:'くさる', type:'I', level:'N2', meaning:'腐烂' },
  { kanji:'くっつく', kana:'くっつく', type:'I', level:'N2', meaning:'粘住' },
  { kanji:'工夫する', kana:'くふうする', type:'III', level:'N2', meaning:'下功夫' },
  { kanji:'組み立てる', kana:'くみたてる', type:'II', level:'N2', meaning:'组装' },
  { kanji:'暮らす', kana:'くらす', type:'I', level:'N2', meaning:'生活' },
  { kanji:'繰り返す', kana:'くりかえす', type:'I', level:'N2', meaning:'重复' },
  { kanji:'経営する', kana:'けいえいする', type:'III', level:'N2', meaning:'经营' },
  { kanji:'削る', kana:'けずる', type:'I', level:'N2', meaning:'削、削减' },
  { kanji:'異なる', kana:'ことなる', type:'I', level:'N2', meaning:'不同' },
  { kanji:'好む', kana:'このむ', type:'I', level:'N2', meaning:'喜好' },
  { kanji:'こぼす', kana:'こぼす', type:'I', level:'N2', meaning:'弄洒' },
  { kanji:'壊す', kana:'こわす', type:'I', level:'N2', meaning:'弄坏' },
  { kanji:'壊れる', kana:'こわれる', type:'II', level:'N2', meaning:'坏掉' },
  { kanji:'逆らう', kana:'さからう', type:'I', level:'N2', meaning:'违背' },
  { kanji:'支える', kana:'ささえる', type:'II', level:'N2', meaning:'支撑' },
  { kanji:'指す', kana:'さす', type:'I', level:'N2', meaning:'指' },
  { kanji:'去る', kana:'さる', type:'I', level:'N2', meaning:'离开' },
  { kanji:'賛成する', kana:'さんせいする', type:'III', level:'N2', meaning:'赞成' },
  { kanji:'しがみつく', kana:'しがみつく', type:'I', level:'N2', meaning:'紧紧抱住' },
  { kanji:'しかる', kana:'しかる', type:'I', level:'N2', meaning:'责备' },
  { kanji:'沈む', kana:'しずむ', type:'I', level:'N2', meaning:'沉没' },
  { kanji:'従う', kana:'したがう', type:'I', level:'N2', meaning:'遵从' },
  { kanji:'親しむ', kana:'したしむ', type:'I', level:'N2', meaning:'亲近' },
  { kanji:'しつける', kana:'しつける', type:'II', level:'N2', meaning:'管教' },
  { kanji:'しゃがむ', kana:'しゃがむ', type:'I', level:'N2', meaning:'蹲下' },
  { kanji:'主張する', kana:'しゅちょうする', type:'III', level:'N2', meaning:'主张' },
  { kanji:'所属する', kana:'しょぞくする', type:'III', level:'N2', meaning:'所属' },
  { kanji:'制限する', kana:'せいげんする', type:'III', level:'N2', meaning:'限制' },
  { kanji:'成功する', kana:'せいこうする', type:'III', level:'N2', meaning:'成功' },
  { kanji:'製造する', kana:'せいぞうする', type:'III', level:'N2', meaning:'制造' },
  { kanji:'攻める', kana:'せめる', type:'II', level:'N2', meaning:'攻击' },
  { kanji:'注ぐ', kana:'そそぐ', type:'I', level:'N2', meaning:'注入' },
  { kanji:'存在する', kana:'そんざいする', type:'III', level:'N2', meaning:'存在' },
  { kanji:'対する', kana:'たいする', type:'III', level:'N2', meaning:'面对' },
  { kanji:'戦う', kana:'たたかう', type:'I', level:'N2', meaning:'战斗' },
  { kanji:'抱く', kana:'だく', type:'I', level:'N2', meaning:'抱' },
  { kanji:'訪ねる', kana:'たずねる', type:'II', level:'N2', meaning:'访问' },
  { kanji:'尋ねる', kana:'たずねる', type:'II', level:'N2', meaning:'询问' },
  { kanji:'畳む', kana:'たたむ', type:'I', level:'N2', meaning:'折叠' },
  { kanji:'立ち上がる', kana:'たちあがる', type:'I', level:'N2', meaning:'站起来' },
  { kanji:'経つ', kana:'たつ', type:'I', level:'N2', meaning:'经过（时间）' },
  { kanji:'達成する', kana:'たっせいする', type:'III', level:'N2', meaning:'达成' },
  { kanji:'たまる', kana:'たまる', type:'I', level:'N2', meaning:'积攒' },
  { kanji:'試す', kana:'ためす', type:'I', level:'N2', meaning:'尝试' },
  { kanji:'頼る', kana:'たよる', type:'I', level:'N2', meaning:'依靠' },
  { kanji:'散らかす', kana:'ちらかす', type:'I', level:'N2', meaning:'弄乱' },
  { kanji:'努める', kana:'つとめる', type:'II', level:'N2', meaning:'努力' },
  { kanji:'つながる', kana:'つながる', type:'I', level:'N2', meaning:'连接' },
  { kanji:'つぶやく', kana:'つぶやく', type:'I', level:'N2', meaning:'嘟囔' },
  { kanji:'提案する', kana:'ていあんする', type:'III', level:'N2', meaning:'提议' },
  { kanji:'出会う', kana:'であう', type:'I', level:'N2', meaning:'偶遇' },
  { kanji:'出来上がる', kana:'できあがる', type:'I', level:'N2', meaning:'完成' },
  { kanji:'問う', kana:'とう', type:'I', level:'N2', exceptions:{te:'とうて',ta:'とうた'}, meaning:'问' },
  { kanji:'解く', kana:'とく', type:'I', level:'N2', meaning:'解开' },
  { kanji:'遂げる', kana:'とげる', type:'II', level:'N2', meaning:'完成' },
  { kanji:'取り消す', kana:'とりけす', type:'I', level:'N2', meaning:'取消' },
  { kanji:'取り出す', kana:'とりだす', type:'I', level:'N2', meaning:'取出' },
  { kanji:'治す', kana:'なおす', type:'I', level:'N2', meaning:'治疗' },
  { kanji:'流す', kana:'ながす', type:'I', level:'N2', meaning:'冲走' },
  { kanji:'なぐる', kana:'なぐる', type:'I', level:'N2', meaning:'殴打' },
  { kanji:'なめる', kana:'なめる', type:'II', level:'N2', meaning:'舔、尝' },
  { kanji:'悩む', kana:'なやむ', type:'I', level:'N2', meaning:'烦恼' },
  { kanji:'匂う', kana:'におう', type:'I', level:'N2', meaning:'有味道' },
  { kanji:'逃がす', kana:'にがす', type:'I', level:'N2', meaning:'放跑' },
  { kanji:'憎む', kana:'にくむ', type:'I', level:'N2', meaning:'憎恨' },
  { kanji:'濁る', kana:'にごる', type:'I', level:'N2', meaning:'浑浊' },
  { kanji:'睨む', kana:'にらむ', type:'I', level:'N2', meaning:'瞪' },
  { kanji:'抜く', kana:'ぬく', type:'I', level:'N2', meaning:'拔出' },
  { kanji:'願う', kana:'ねがう', type:'I', level:'N2', meaning:'恳求' },
  { kanji:'眠る', kana:'ねむる', type:'I', level:'N2', meaning:'睡着' },
  { kanji:'乗り越える', kana:'のりこえる', type:'II', level:'N2', meaning:'越过' },
  { kanji:'励ます', kana:'はげます', type:'I', level:'N2', meaning:'鼓励' },
  { kanji:'挟む', kana:'はさむ', type:'I', level:'N2', meaning:'夹' },
  { kanji:'外れる', kana:'はずれる', type:'II', level:'N2', meaning:'脱离' },
  { kanji:'放す', kana:'はなす', type:'I', level:'N2', meaning:'放开' },
  { kanji:'離れる', kana:'はなれる', type:'II', level:'N2', meaning:'分离' },
  { kanji:'控える', kana:'ひかえる', type:'II', level:'N2', meaning:'抑制、暂缓' },
  { kanji:'引き出す', kana:'ひきだす', type:'I', level:'N2', meaning:'抽出' },
  { kanji:'ひっくり返す', kana:'ひっくりかえす', type:'I', level:'N2', meaning:'翻转' },
  { kanji:'振る', kana:'ふる', type:'I', level:'N2', meaning:'挥动' },
  { kanji:'隔てる', kana:'へだてる', type:'II', level:'N2', meaning:'隔开' },
  { kanji:'保つ', kana:'たもつ', type:'I', level:'N2', meaning:'保持' },
  { kanji:'まぶす', kana:'まぶす', type:'I', level:'N2', meaning:'裹上' },
  { kanji:'見上げる', kana:'みあげる', type:'II', level:'N2', meaning:'仰望' },
  { kanji:'見送る', kana:'みおくる', type:'I', level:'N2', meaning:'送别' },
  { kanji:'満たす', kana:'みたす', type:'I', level:'N2', meaning:'满足' },
  { kanji:'結ぶ', kana:'むすぶ', type:'I', level:'N2', meaning:'连接' },
  { kanji:'無視する', kana:'むしする', type:'III', level:'N2', meaning:'无视' },
  { kanji:'召し上がる', kana:'めしあがる', type:'I', level:'N2', meaning:'吃/喝（尊敬）' },
  { kanji:'持てる', kana:'もてる', type:'II', level:'N2', meaning:'受欢迎' },
  { kanji:'もらう', kana:'もらう', type:'I', level:'N2', meaning:'得到' },
  { kanji:'焼く', kana:'やく', type:'I', level:'N2', meaning:'烧、烤' },
  { kanji:'雇う', kana:'やとう', type:'I', level:'N2', meaning:'雇用' },
  { kanji:'輸出する', kana:'ゆしゅつする', type:'III', level:'N2', meaning:'出口' },
  { kanji:'汚れる', kana:'よごれる', type:'II', level:'N2', meaning:'变脏（自动）' },
  { kanji:'寄る', kana:'よる', type:'I', level:'N2', meaning:'靠近' },
  { kanji:'分かつ', kana:'わかつ', type:'I', level:'N2', meaning:'区分' },
  { kanji:'割る', kana:'わる', type:'I', level:'N2', meaning:'弄碎' },
  { kanji:'割れる', kana:'われる', type:'II', level:'N2', meaning:'破碎' },

  // 第二批：补足基础常用动词与N2重点动词（均带初稿标签）
  { kanji:'浴びる', kana:'あびる', type:'II', level:'N5', meaning:'洗澡、淋浴', daily:'high', exam:'common', trans:'vt' },
  { kanji:'泳ぐ', kana:'およぐ', type:'I', level:'N5', meaning:'游泳', daily:'normal', exam:'supplement', trans:'vi' },
  { kanji:'急ぐ', kana:'いそぐ', type:'I', level:'N5', meaning:'赶紧、赶路', daily:'high', exam:'common', trans:'both' },
  { kanji:'終わる', kana:'おわる', type:'I', level:'N5', meaning:'结束', daily:'high', exam:'common', trans:'vi' },
  { kanji:'乗る', kana:'のる', type:'I', level:'N5', meaning:'乘坐', daily:'high', exam:'common', trans:'vi' },
  { kanji:'降りる', kana:'おりる', type:'II', level:'N5', meaning:'下车、下来', daily:'high', exam:'common', trans:'vi' },
  { kanji:'着く', kana:'つく', type:'I', level:'N5', meaning:'到达', daily:'high', exam:'common', trans:'vi' },
  { kanji:'忘れる', kana:'わすれる', type:'II', level:'N5', meaning:'忘记', daily:'high', exam:'common', trans:'vt' },
  { kanji:'送る', kana:'おくる', type:'I', level:'N5', meaning:'发送、送行', daily:'high', exam:'common', trans:'vt' },
  { kanji:'習う', kana:'ならう', type:'I', level:'N5', meaning:'学习', daily:'high', exam:'common', trans:'vt' },
  { kanji:'勉強する', kana:'べんきょうする', type:'III', level:'N5', meaning:'学习', daily:'high', exam:'common', trans:'both' },
  { kanji:'掃除する', kana:'そうじする', type:'III', level:'N5', meaning:'打扫', daily:'high', exam:'supplement', trans:'both' },
  { kanji:'洗濯する', kana:'せんたくする', type:'III', level:'N5', meaning:'洗衣服', daily:'high', exam:'supplement', trans:'both' },
  { kanji:'料理する', kana:'りょうりする', type:'III', level:'N5', meaning:'做饭', daily:'high', exam:'supplement', trans:'both' },
  { kanji:'散歩する', kana:'さんぽする', type:'III', level:'N5', meaning:'散步', daily:'normal', exam:'supplement', trans:'vi' },
  { kanji:'乗せる', kana:'のせる', type:'II', level:'N4', meaning:'让…乘坐、装载', daily:'normal', exam:'common', trans:'vt' },
  { kanji:'止める', kana:'とめる', type:'II', level:'N4', meaning:'使停止、停放', daily:'high', exam:'common', trans:'vt' },
  { kanji:'変わる', kana:'かわる', type:'I', level:'N4', meaning:'改变', daily:'high', exam:'common', trans:'vi' },
  { kanji:'変える', kana:'かえる', type:'II', level:'N4', meaning:'改变', daily:'high', exam:'common', trans:'vt' },
  { kanji:'起こす', kana:'おこす', type:'I', level:'N4', meaning:'叫醒、引起', daily:'high', exam:'common', trans:'vt' },
  { kanji:'育つ', kana:'そだつ', type:'I', level:'N4', meaning:'成长', daily:'normal', exam:'common', trans:'vi' },
  { kanji:'植える', kana:'うえる', type:'II', level:'N4', meaning:'种植', daily:'normal', exam:'supplement', trans:'vt' },
  { kanji:'遅れる', kana:'おくれる', type:'II', level:'N4', meaning:'迟到、晚到', daily:'high', exam:'common', trans:'vi' },
  { kanji:'着替える', kana:'きがえる', type:'II', level:'N4', meaning:'换衣服', daily:'normal', exam:'supplement', trans:'both' },
  { kanji:'終える', kana:'おえる', type:'II', level:'N3', meaning:'结束、完成', daily:'normal', exam:'common', trans:'vt' },
  { kanji:'付く', kana:'つく', type:'I', level:'N4', meaning:'附着、带有', daily:'normal', exam:'common', trans:'vi', nonVolitional:true },
  { kanji:'切れる', kana:'きれる', type:'II', level:'N4', meaning:'断、被切断', daily:'high', exam:'common', trans:'vi', nonVolitional:true },
  { kanji:'折る', kana:'おる', type:'I', level:'N4', meaning:'折断、折叠', daily:'normal', exam:'supplement', trans:'vt' },
  { kanji:'汚す', kana:'よごす', type:'I', level:'N4', meaning:'弄脏', daily:'normal', exam:'common', trans:'vt' },
  { kanji:'曲げる', kana:'まげる', type:'II', level:'N4', meaning:'弄弯、弯曲', daily:'normal', exam:'supplement', trans:'vt' },
  { kanji:'冷える', kana:'ひえる', type:'II', level:'N4', meaning:'变凉', daily:'high', exam:'common', trans:'vi', nonVolitional:true },
  { kanji:'温まる', kana:'あたたまる', type:'I', level:'N4', meaning:'变暖', daily:'normal', exam:'common', trans:'vi', nonVolitional:true },
  { kanji:'乾かす', kana:'かわかす', type:'I', level:'N4', meaning:'弄干、晾干', daily:'normal', exam:'supplement', trans:'vt' },
  { kanji:'焼ける', kana:'やける', type:'II', level:'N4', meaning:'烧好、烤好', daily:'normal', exam:'common', trans:'vi', nonVolitional:true },
  { kanji:'生む', kana:'うむ', type:'I', level:'N3', meaning:'生、产生', daily:'normal', exam:'common', trans:'vt' },
  { kanji:'参加する', kana:'さんかする', type:'III', level:'N4', meaning:'参加', daily:'high', exam:'common', trans:'vi' },
  { kanji:'出発する', kana:'しゅっぱつする', type:'III', level:'N4', meaning:'出发', daily:'high', exam:'common', trans:'vi' },
  { kanji:'到着する', kana:'とうちゃくする', type:'III', level:'N4', meaning:'到达', daily:'high', exam:'common', trans:'vi' },
  { kanji:'予約する', kana:'よやくする', type:'III', level:'N4', meaning:'预约', daily:'high', exam:'common', trans:'vt' },
  { kanji:'注文する', kana:'ちゅうもんする', type:'III', level:'N4', meaning:'点餐、订购', daily:'high', exam:'common', trans:'vt' },
  { kanji:'案内する', kana:'あんないする', type:'III', level:'N4', meaning:'引导、介绍', daily:'high', exam:'common', trans:'vt' },
  { kanji:'利用する', kana:'りようする', type:'III', level:'N3', meaning:'利用、使用', daily:'high', exam:'common', trans:'vt' },
  { kanji:'連絡する', kana:'れんらくする', type:'III', level:'N4', meaning:'联系', daily:'high', exam:'common', trans:'both' },
  { kanji:'確認する', kana:'かくにんする', type:'III', level:'N3', meaning:'确认', daily:'high', exam:'common', trans:'vt' },
  { kanji:'相談する', kana:'そうだんする', type:'III', level:'N4', meaning:'商量、咨询', daily:'high', exam:'common', trans:'both' },
  { kanji:'申し込む', kana:'もうしこむ', type:'I', level:'N3', meaning:'申请、报名', daily:'high', exam:'common', trans:'vt' },
  { kanji:'断る', kana:'ことわる', type:'I', level:'N3', meaning:'拒绝、谢绝', daily:'high', exam:'common', trans:'vt' },
  { kanji:'感じる', kana:'かんじる', type:'II', level:'N3', meaning:'感觉、感到', daily:'high', exam:'common', trans:'vt' },
  { kanji:'向かう', kana:'むかう', type:'I', level:'N3', meaning:'面向、前往', daily:'high', exam:'common', trans:'vi' },
  { kanji:'向ける', kana:'むける', type:'II', level:'N3', meaning:'朝向、面向', daily:'normal', exam:'common', trans:'vt' },

  { kanji:'通じる', kana:'つうじる', type:'II', level:'N2', meaning:'相通、通晓', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'通す', kana:'とおす', type:'I', level:'N2', meaning:'使通过、贯彻', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'求める', kana:'もとめる', type:'II', level:'N2', meaning:'寻求、要求', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'認める', kana:'みとめる', type:'II', level:'N2', meaning:'承认、认可', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'目指す', kana:'めざす', type:'I', level:'N2', meaning:'以…为目标', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'述べる', kana:'のべる', type:'II', level:'N2', meaning:'陈述、叙述', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'防ぐ', kana:'ふせぐ', type:'I', level:'N2', meaning:'防止、防御', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'避ける', kana:'さける', type:'II', level:'N2', meaning:'避开、避免', daily:'high', exam:'focus', trans:'vt' },
  { kanji:'生じる', kana:'しょうじる', type:'II', level:'N2', meaning:'产生、发生', daily:'normal', exam:'focus', trans:'both', nonVolitional:true },
  { kanji:'占める', kana:'しめる', type:'II', level:'N2', meaning:'占据、占有', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'設ける', kana:'もうける', type:'II', level:'N2', meaning:'设置、设立', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'備える', kana:'そなえる', type:'II', level:'N2', meaning:'准备、配备', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'伴う', kana:'ともなう', type:'I', level:'N2', meaning:'伴随、带有', daily:'normal', exam:'focus', trans:'both' },
  { kanji:'果たす', kana:'はたす', type:'I', level:'N2', meaning:'完成、履行', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'図る', kana:'はかる', type:'I', level:'N2', meaning:'谋求、设法', daily:'low', exam:'focus', trans:'vt' },
  { kanji:'優れる', kana:'すぐれる', type:'II', level:'N2', meaning:'优秀、出色', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'迫る', kana:'せまる', type:'I', level:'N2', meaning:'逼近、迫近', daily:'normal', exam:'focus', trans:'vi' },
  { kanji:'欠ける', kana:'かける', type:'II', level:'N2', meaning:'缺少、欠缺', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'欠かす', kana:'かかす', type:'I', level:'N2', meaning:'缺少、中断', daily:'low', exam:'focus', trans:'vt' },
  { kanji:'取り組む', kana:'とりくむ', type:'I', level:'N2', meaning:'致力于、着手', daily:'normal', exam:'focus', trans:'vi' },
  { kanji:'取り入れる', kana:'とりいれる', type:'II', level:'N2', meaning:'采用、引进', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'取り上げる', kana:'とりあげる', type:'II', level:'N2', meaning:'拿起、采用、提出', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'取り戻す', kana:'とりもどす', type:'I', level:'N2', meaning:'取回、恢复', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'見直す', kana:'みなおす', type:'I', level:'N2', meaning:'重新审视、改进', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'見失う', kana:'みうしなう', type:'I', level:'N2', meaning:'看丢、迷失', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'広がる', kana:'ひろがる', type:'I', level:'N2', meaning:'扩大、传播', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'広げる', kana:'ひろげる', type:'II', level:'N2', meaning:'扩大、展开', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'深まる', kana:'ふかまる', type:'I', level:'N2', meaning:'加深', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'深める', kana:'ふかめる', type:'II', level:'N2', meaning:'加深、深化', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'高まる', kana:'たかまる', type:'I', level:'N2', meaning:'提高、高涨', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'高める', kana:'たかめる', type:'II', level:'N2', meaning:'提高、增强', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'強まる', kana:'つよまる', type:'I', level:'N2', meaning:'增强', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'強める', kana:'つよめる', type:'II', level:'N2', meaning:'加强、增强', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'弱まる', kana:'よわまる', type:'I', level:'N2', meaning:'减弱', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'弱める', kana:'よわめる', type:'II', level:'N2', meaning:'减弱、削弱', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'伸びる', kana:'のびる', type:'II', level:'N2', meaning:'伸长、增长', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'伸ばす', kana:'のばす', type:'I', level:'N2', meaning:'延伸、增长', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'縮む', kana:'ちぢむ', type:'I', level:'N2', meaning:'缩小、收缩', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'縮める', kana:'ちぢめる', type:'II', level:'N2', meaning:'缩短、缩小', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'抜ける', kana:'ぬける', type:'II', level:'N2', meaning:'脱落、遗漏、穿过', daily:'normal', exam:'focus', trans:'vi' },
  { kanji:'溢れる', kana:'あふれる', type:'II', level:'N2', meaning:'溢出、充满', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'預ける', kana:'あずける', type:'II', level:'N2', meaning:'寄存、托付', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'焦る', kana:'あせる', type:'I', level:'N2', meaning:'着急、焦躁', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'味わう', kana:'あじわう', type:'I', level:'N2', meaning:'品味、体验', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'あきれる', kana:'あきれる', type:'II', level:'N2', meaning:'惊讶、无语', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'慌てる', kana:'あわてる', type:'II', level:'N2', meaning:'慌张、匆忙', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'至る', kana:'いたる', type:'I', level:'N2', meaning:'到达、至', daily:'low', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'浮かぶ', kana:'うかぶ', type:'I', level:'N2', meaning:'浮现、想起', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'浮かべる', kana:'うかべる', type:'II', level:'N2', meaning:'使浮起、浮现', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'訴える', kana:'うったえる', type:'II', level:'N2', meaning:'诉说、起诉', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'奪う', kana:'うばう', type:'I', level:'N2', meaning:'夺取、剥夺', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'埋まる', kana:'うまる', type:'I', level:'N2', meaning:'被填满、埋着', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'埋める', kana:'うめる', type:'II', level:'N2', meaning:'填埋、填补', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'覆う', kana:'おおう', type:'I', level:'N2', meaning:'覆盖、笼罩', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'押さえる', kana:'おさえる', type:'II', level:'N2', meaning:'按住、掌握', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'劣る', kana:'おとる', type:'I', level:'N2', meaning:'不如、劣于', daily:'low', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'衰える', kana:'おとろえる', type:'II', level:'N2', meaning:'衰退、衰弱', daily:'low', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'溺れる', kana:'おぼれる', type:'II', level:'N2', meaning:'溺水、沉迷', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'及ぼす', kana:'およぼす', type:'I', level:'N2', meaning:'波及、带来影响', daily:'low', exam:'focus', trans:'vt' },
  { kanji:'抱える', kana:'かかえる', type:'II', level:'N2', meaning:'抱着、承担', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'稼ぐ', kana:'かせぐ', type:'I', level:'N2', meaning:'赚钱、争取', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'傾く', kana:'かたむく', type:'I', level:'N2', meaning:'倾斜、倾向', daily:'low', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'傷つける', kana:'きずつける', type:'II', level:'N2', meaning:'伤害、弄伤', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'崩す', kana:'くずす', type:'I', level:'N2', meaning:'拆散、弄乱', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'崩れる', kana:'くずれる', type:'II', level:'N2', meaning:'崩塌、崩溃', daily:'normal', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'砕く', kana:'くだく', type:'I', level:'N2', meaning:'打碎、粉碎', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'砕ける', kana:'くだける', type:'II', level:'N2', meaning:'破碎、变随和', daily:'low', exam:'focus', trans:'vi', nonVolitional:true },
  { kanji:'くっつける', kana:'くっつける', type:'II', level:'N2', meaning:'粘上、连接', daily:'normal', exam:'focus', trans:'vt' },
  { kanji:'悔やむ', kana:'くやむ', type:'I', level:'N2', meaning:'后悔、悼念', daily:'low', exam:'focus', trans:'vt' },
  { kanji:'狂う', kana:'くるう', type:'I', level:'N2', meaning:'发狂、失常', daily:'low', exam:'focus', trans:'vi', nonVolitional:true }
];

// ========== 初稿词频标签 ==========
// 这里只放一批代表词用于测试入口、筛选和标签。未列出的词保留在完整词库中，标记为「待补充」。
// daily: high=日常常用, normal=日常一般, low=日常低频
// exam: focus=JLPT重点, common=JLPT常见, supplement=考试补充
var verbProfiles = {
  '会う':{daily:'high',exam:'common'}, '行く':{daily:'high',exam:'common'}, '来る':{daily:'high',exam:'common'},
  'する':{daily:'high',exam:'common'}, '食べる':{daily:'high',exam:'common'}, '飲む':{daily:'high',exam:'common'},
  '見る':{daily:'high',exam:'common'}, '聞く':{daily:'high',exam:'common'}, '話す':{daily:'high',exam:'common'},
  '読む':{daily:'high',exam:'common'}, '書く':{daily:'high',exam:'common'}, '買う':{daily:'high',exam:'common'},
  '使う':{daily:'high',exam:'common'}, '思う':{daily:'high',exam:'common'}, '分かる':{daily:'high',exam:'common'},
  '入る':{daily:'high',exam:'common'}, '出る':{daily:'high',exam:'common'}, '起きる':{daily:'high',exam:'common'},
  '寝る':{daily:'high',exam:'common'}, '働く':{daily:'high',exam:'common'}, '休む':{daily:'high',exam:'common'},
  '持つ':{daily:'high',exam:'common'}, '待つ':{daily:'high',exam:'common'}, '帰る':{daily:'high',exam:'common'},
  '開ける':{daily:'high',exam:'common'}, '閉める':{daily:'high',exam:'common'},

  '遊ぶ':{daily:'normal',exam:'supplement'}, '洗う':{daily:'normal',exam:'supplement'}, '歌う':{daily:'normal',exam:'supplement'},
  '笑う':{daily:'normal',exam:'supplement'}, '泣く':{daily:'normal',exam:'supplement'}, '走る':{daily:'normal',exam:'supplement'},
  '座る':{daily:'normal',exam:'supplement'}, '立つ':{daily:'normal',exam:'supplement'},

  '決める':{daily:'high',exam:'common'}, '決まる':{daily:'high',exam:'common'},
  '続ける':{daily:'high',exam:'common'}, '続く':{daily:'high',exam:'common'},
  '伝える':{daily:'high',exam:'common'}, '伝わる':{daily:'normal',exam:'common'},
  '届ける':{daily:'normal',exam:'common'}, '届く':{daily:'high',exam:'common'},
  '選ぶ':{daily:'high',exam:'common'}, '比べる':{daily:'normal',exam:'common'}, '受ける':{daily:'high',exam:'common'},
  '調べる':{daily:'high',exam:'common'}, '慣れる':{daily:'high',exam:'common'}, '間に合う':{daily:'high',exam:'common'},
  '見つける':{daily:'high',exam:'common'}, '見つかる':{daily:'high',exam:'common'},

  '扱う':{daily:'normal',exam:'focus'}, '補う':{daily:'normal',exam:'focus'}, '省く':{daily:'normal',exam:'focus'},
  '維持する':{daily:'normal',exam:'focus'}, '意識する':{daily:'normal',exam:'focus'}, '受け入れる':{daily:'normal',exam:'focus'},
  '受け取る':{daily:'high',exam:'focus'}, '促す':{daily:'low',exam:'focus'}, '達成する':{daily:'normal',exam:'focus'},
  '遂げる':{daily:'low',exam:'focus'}, '保つ':{daily:'normal',exam:'focus'}, '支える':{daily:'normal',exam:'focus'},
  '及ぶ':{daily:'low',exam:'focus'}, '落ち着く':{daily:'high',exam:'focus'}, '控える':{daily:'normal',exam:'focus'},
  '満たす':{daily:'normal',exam:'focus'}, '異なる':{daily:'normal',exam:'focus'}, '繰り返す':{daily:'high',exam:'focus'},
  '組み立てる':{daily:'normal',exam:'focus'}, '取り消す':{daily:'normal',exam:'focus'}, '見送る':{daily:'normal',exam:'focus'},
  '見上げる':{daily:'normal',exam:'focus'}, '省みる':{daily:'low',exam:'focus'}, '隔てる':{daily:'low',exam:'focus'},
  '帯びる':{daily:'low',exam:'focus'}, '分かつ':{daily:'low',exam:'focus'}
};

var dailyProfileLabels = {high:'日常常用', normal:'日常一般', low:'日常低频', pending:'日常待补充'};
var examProfileLabels = {focus:'JLPT重点', common:'JLPT常见', supplement:'考试补充', pending:'JLPT待补充'};

function getVerbProfile(verb) {
  return verbProfiles[verb.kanji] || (verb.daily && verb.exam ? {daily:verb.daily, exam:verb.exam} : {daily:'pending', exam:'pending'});
}

// ========== 自他动词分类 ==========
// bothTransitiveVerbs 中的动词可作自动词或他动词，选择任一分类时都会纳入。
var intransitiveVerbs = [
  '会う','開く','遊ぶ','ある','歩く','行く','いる','生まれる','起きる','帰る','消える','来る','答える','困る','咲く','死ぬ','閉まる','住む','座る','立つ','違う','勤める','出る','飛ぶ','止まる','無くなる','並ぶ','なる','寝る','登る','入る','始まる','走る','働く','降る','曲がる','分かる','渡る',
  '合う','上がる','集まる','謝る','安心する','怒る','落ちる','勝つ','通う','決まる','暮れる','下がる','騒ぐ','触る','過ぎる','進む','滑る','倒れる','足りる','疲れる','続く','出かける','出来る','泊まる','直る','治る','泣く','慣れる','逃げる','似る','残る','増える','減る','負ける','間に合う','回る','見つかる','戻る','痩せる','止む','喜ぶ','別れる','笑う',
  '飽きる','当たる','生きる','いらっしゃる','動く','映る','驚く','下りる','折れる','返る','隠れる','聞こえる','喧嘩する','こぼれる','込む','すれ違う','付き合う','伝わる','通る','届く','飛び込む','亡くなる','似合う','参る','間違う','見える','役立つ','沸く',
  '合図する','憧れる','当てはまる','暴れる','余る','移住する','引退する','落ち着く','及ぶ','重なる','固まる','渇く','乾く','気付く','腐る','くっつく','暮らす','異なる','去る','賛成する','しがみつく','沈む','従う','親しむ','所属する','成功する','存在する','対する','戦う','立ち上がる','経つ','たまる','頼る','努める','つながる','出会う','出来上がる','悩む','匂う','濁る','眠る','外れる','離れる','持てる','汚れる','寄る','割れる'
];
var bothTransitiveVerbs = ['する','休む','注意する','約束する','育児する','工夫する','思い込む'];

function getTransitivity(verb) {
  if (verb.trans) return verb.trans;
  if (bothTransitiveVerbs.indexOf(verb.kanji) !== -1) return 'both';
  return intransitiveVerbs.indexOf(verb.kanji) !== -1 ? 'vi' : 'vt';
}

function matchesTransitivity(verb) {
  var trans = getTransitivity(verb);
  if (transTypes.length === 0) return false;
  return trans === 'both' || transTypes.indexOf(trans) !== -1;
}

// 本身已经表达可能或状态的动词，不再机械生成错误的“可能形”。
function isValidFormForVerb(verb, form) {
  if (form === 'potential' && ['ある','わかる','できる','きこえる','みえる','もてる'].indexOf(verb.kana) !== -1) return false;
  return true;
}

// 常用与考试价值是针对「这个词＋这个变形」判断，不对整类变形一刀切。
var limitedAdvancedFormVerbs = ['ある','出来る','見える','聞こえる','持てる','異なる','存在する','足りる'];
var commandRelevantVerbs = ['行く','来る','見る','聞く','言う','話す','書く','読む','食べる','飲む','待つ','止まる','入る','出る','触る','逃げる','立つ','座る','休む'];
var indirectPassiveExamVerbs = ['降る','来る','行く','休む','騒ぐ','泣く','死ぬ'];
var commonPassiveVerbs = ['言う','聞く','呼ぶ','見る','褒める','しかる','誘う','選ぶ','使う','頼む','教える','注意する','紹介する','招く','雇う'];
var commonCausativeVerbs = ['待つ','行く','来る','食べる','飲む','遊ぶ','働く','休む','寝る','起きる'];

function getFormPracticeStatus(verb, form) {
  if (!isValidFormForVerb(verb, form)) return 'invalid';
  if (['masu','te','ta','nai','ba'].indexOf(form) !== -1) return 'core';
  if (form === 'potential' || form === 'volitional') return verb.nonVolitional ? 'rare' : 'core';
  if (form === 'passive') {
    if (commonPassiveVerbs.indexOf(verb.kanji) !== -1) return 'core';
    if (getTransitivity(verb) !== 'vi' || indirectPassiveExamVerbs.indexOf(verb.kanji) !== -1) return 'exam';
    return 'rare';
  }
  if (form === 'causative') {
    if (commonCausativeVerbs.indexOf(verb.kanji) !== -1) return 'core';
    return !verb.nonVolitional && limitedAdvancedFormVerbs.indexOf(verb.kanji) === -1 ? 'exam' : 'rare';
  }
  if (form === 'causativePassive') {
    return !verb.nonVolitional && limitedAdvancedFormVerbs.indexOf(verb.kanji) === -1 ? 'exam' : 'rare';
  }
  if (form === 'imperative' || form === 'prohibition') {
    return commandRelevantVerbs.indexOf(verb.kanji) !== -1 ? 'exam' : 'rare';
  }
  return 'rare';
}
